=== UbiSOA/UbiSOA/web/pub/schemas/v1/discovery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:ubisoa:discovery"
	xmlns="urn:ubisoa:discovery"
	elementFormDefault="qualified">
	
	<xs:element name="result">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="services" type="servicesType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="servicesType">
		<xs:sequence>
			<xs:element ref="service" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="service">
		<xs:complexType>
			<xs:all>
				<xs:element name="published" minOccurs="0" type="xs:dateTime"/>
				<xs:element name="updated" minOccurs="0" type="xs:dateTime"/>
				<xs:element name="source" type="sourceType"/>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element name="host" type="xs:string"/>
				<xs:element name="port" type="xs:integer"/>
				<xs:element name="base_uri" minOccurs="0" type="xs:string"/>
				<xs:element name="coordinates" minOccurs="0" type="xs:anyType"/>
				<xs:element name="hub" minOccurs="0" type="xs:string"/>
				<xs:element name="implements" type="implementsType"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="sourceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bonjour"/>
			<xs:enumeration value="user"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="implementsType">
		<xs:sequence>
			<xs:element name="interface" minOccurs="0" maxOccurs="unbounded" type="xs:anyURI"/>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== UbiSOA/UbiSOA/web/pub/samples/representations/discovery-services.xml
<?xml version="1.0" encoding="UTF-8"?>
<result xmlns="urn:ubisoa:discovery"
	xmlns:georss="http://www.georss.org/georss"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:ubisoa:discovery http://schemas.ubisoa.net/v1/discovery.xsd">
	<services>
		<service>
			<published>2010-08-24T07:05:00-07:00</published>
			<updated>2010-08-24T07:05:00-07:00</updated>
			<host>localhost</host>
			<port>8081</port>
			<baseUri>/api</baseUri>
			<hub>http://pubsubhubbub.appspot.com/</hub>
			<name>Alpha Service</name>
			<description>A Test Service</description>
			<implements>
				<interface>http://interfaces.ubisoa.net/v1/sensing.wadl</interface>
				<interface>http://interfaces.ubisoa.net/v1/push.wadl</interface>
			</implements>
			<coordinates>
				<georss:point>31.835525 -116.616083</georss:point>
			</coordinates>
			<source>auto</source>
		</service>
		<service>
			<published>2010-08-24T07:05:00-07:00</published>
			<updated>2010-08-24T07:05:00-07:00</updated>
			<name>Bravo Service</name>
			<description>Another Test Service</description>
			<host>localhost</host>
			<port>8082</port>
			<source>auto</source>
			<hub>http://pubsubhubbub.appspot.com/</hub>
			<implements>
				<interface>http://interfaces.ubisoa.net/v1/autoid.wadl</interface>
				<interface>http://interfaces.ubisoa.net/v1/push.wadl</interface>
			</implements>
			<coordinates>
				<georss:point>31.835525 -116.616083</georss:point>
			</coordinates>
		</service>
		<service>
			<published>2010-08-24T07:05:00-07:00</published>
			<updated>2010-08-24T07:05:00-07:00</updated>
			<source>user</source>
			<host>localhost</host>
			<port>8083</port>
			<name>Charlie Service</name>
			<description>And Other Test Service</description>
			<implements>
				<interface>http://interfaces.ubisoa.net/v1/control.wadl</interface>
			</implements>
		</service>
	</services>
</result>
