=== UbiSOA/UbiSOA/web/pub/schemas/V1/discovery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ubisoa:discovery" xmlns="urn:ubisoa:discovery" elementFormDefault="qualified">
	
	<xs:element name="result">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="services" type="servicesType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="servicesType">
		<xs:sequence>
			<xs:element name="service" minOccurs="0" maxOccurs="unbounded" type="serviceType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="serviceType">
		<xs:all>
			<xs:element name="source" type="sourceType"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="host" type="xs:string"/>
			<xs:element name="port" type="xs:integer"/>
			<xs:element name="base_uri" type="xs:string"/>
			<xs:element name="implements" type="implementsType"/>
			<xs:element name="coordinates" type="xs:anyType"/>
			<xs:element name="hub" type="xs:string"/>
		</xs:all>
	</xs:complexType>
	
	<xs:simpleType name="sourceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bonjour"/>
			<xs:enumeration value="user"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="implementsType">
		<xs:sequence>
			<xs:element name="interface" minOccurs="0" maxOccurs="unbounded" type="xs:anyURI"/>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== UbiSOA/UbiSOA/web/pub/samples/representations/discovery-service.xml
<?xml version="1.0" encoding="UTF-8"?>
<service xmlns="urn:ubisoa:discovery"
	xmlns:georss="http://www.georss.org/georss"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:ubisoa:discovery http://schemas.ubisoa.net/v1/discovery.xsd">
	<host>127.0.0.1</host>
	<port>8320</port>
	<baseUri>/api</baseUri>
	<hub>http://pubsubhubbub.appspot.com/</hub>
	<name>Alpha Service</name>
	<description>A Test Sensing Service</description>
	<implements>
		<interface>http://interfaces.ubisoa.net/v1/sensing.wadl</interface>
		<interface>http://interfaces.ubisoa.net/v1/push.wadl</interface>
	</implements>
	<coordinates>
		<georss:point>31.835525 -116.616083</georss:point>
	</coordinates>
	<source>user</source>
</service>
